# Generated by Django 5.2 on 2025-04-25 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likesmodel',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
